# Generated by Django 3.2.4 on 2021-07-09 08:37

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.CharField(max_length=255)),
                ('sub_text', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=home.models.get_hero_slider_img_upload_path)),
                ('btn_to_show', models.CharField(choices=[('membership', 'Membership'), ('volunteering', 'Volunteering'), ('donation', 'Donation')], max_length=50, verbose_name='Button to show')),
            ],
        ),
    ]
