# Generated by Django 3.2.4 on 2021-07-17 08:44

import about.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Member Full Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=about.models.get_member_image_uploadpath, verbose_name='Member Image')),
                ('position', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Address')),
                ('msg', models.CharField(blank=True, max_length=255, null=True)),
                ('fb', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook Profile Link')),
                ('twitter', models.CharField(blank=True, max_length=200, null=True, verbose_name='Twitter Profile Link')),
                ('linkedin', models.CharField(blank=True, max_length=200, null=True, verbose_name='LinkedIn Profile Link')),
                ('date_joined', models.DateField(verbose_name='Date Joined')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Reviewer Full Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=about.models.get_customer_image_uploadpath, verbose_name='Image')),
                ('organization', models.CharField(max_length=100, verbose_name='Reviewer Organization Name')),
                ('position', models.CharField(max_length=50, verbose_name='Reviewer Position')),
                ('testimonial', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated at')),
            ],
        ),
    ]
