# Generated by Django 3.2.4 on 2021-12-03 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='fb',
        ),
        migrations.RemoveField(
            model_name='member',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='member',
            name='twitter',
        ),
    ]
