# Generated by Django 3.2.4 on 2021-12-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20211204_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Address'),
        ),
    ]
