# Generated by Django 3.2.4 on 2021-12-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='display_rank',
            field=models.PositiveIntegerField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
