# Generated by Django 3.2.4 on 2021-12-03 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_auto_20211204_0455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='date_joined',
        ),
    ]
